/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewChucNangChinh;

import java.awt.CardLayout;

/**
 *
 * @author Hoang
 */
public class TrangChu extends javax.swing.JFrame {
    CardLayout cardLayout;
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        cardLayout = (CardLayout) cards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        Menu = new javax.swing.JPanel();
        btnViewSanPham = new javax.swing.JButton();
        btnViewTrangChu = new javax.swing.JButton();
        btnViewNhanVien = new javax.swing.JButton();
        btnViewPhieuGiamGia = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnViewThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        btnViewHoaDon = new javax.swing.JButton();
        cards = new javax.swing.JPanel();
        viewBanHang1 = new viewChucNangChinh.ViewBanHang();
        viewNguoiDung1 = new viewChucNangChinh.ViewNguoiDung();
        viewPhieuGiamGia2 = new viewChucNangChinh.ViewPhieuGiamGia();
        viewHoaDon2 = new viewChucNangChinh.ViewHoaDon();
        viewSanPham1 = new viewChucNangChinh.ViewSanPham();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(49, 77, 100));

        btnViewSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewSanPham.setText("Sản phẩm");
        btnViewSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSanPhamActionPerformed(evt);
            }
        });

        btnViewTrangChu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewTrangChu.setText("Trang Chủ");

        btnViewNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewNhanVien.setText("Người Dùng");
        btnViewNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNhanVienActionPerformed(evt);
            }
        });

        btnViewPhieuGiamGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewPhieuGiamGia.setText("Phiếu giảm giá");
        btnViewPhieuGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPhieuGiamGiaActionPerformed(evt);
            }
        });

        btnBanHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnViewThongKe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewThongKe.setText("Thống kê");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LitZone.png"))); // NOI18N

        lblDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thoat.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        btnViewHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewHoaDon.setText("Hoá Đơn");
        btnViewHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBanHang)
                            .addComponent(btnViewPhieuGiamGia)
                            .addComponent(btnViewNhanVien)
                            .addComponent(btnViewSanPham)
                            .addComponent(btnViewTrangChu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBanHang, btnViewNhanVien, btnViewPhieuGiamGia, btnViewSanPham, btnViewThongKe, btnViewTrangChu});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnViewTrangChu)
                .addGap(18, 18, 18)
                .addComponent(btnViewSanPham)
                .addGap(18, 18, 18)
                .addComponent(btnViewNhanVien)
                .addGap(18, 18, 18)
                .addComponent(btnViewPhieuGiamGia)
                .addGap(18, 18, 18)
                .addComponent(btnBanHang)
                .addGap(18, 18, 18)
                .addComponent(btnViewThongKe)
                .addGap(18, 18, 18)
                .addComponent(btnViewHoaDon)
                .addGap(167, 167, 167)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(Menu);

        cards.setLayout(new java.awt.CardLayout());

        viewBanHang1.setMinimumSize(new java.awt.Dimension(750, 650));
        cards.add(viewBanHang1, "cardBanHang");
        cards.add(viewNguoiDung1, "cardNguoiDung");
        cards.add(viewPhieuGiamGia2, "cardPhieuGiamGia");
        cards.add(viewHoaDon2, "cardHoaDon");
        cards.add(viewSanPham1, "cardSanPham");

        jSplitPane2.setRightComponent(cards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSanPhamActionPerformed
        cardLayout.show(cards,"cardSanPham");
        
    }//GEN-LAST:event_btnViewSanPhamActionPerformed

    private void btnViewNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNhanVienActionPerformed
        cardLayout.show(cards,"cardNguoiDung");
    }//GEN-LAST:event_btnViewNhanVienActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        cardLayout.show(cards,"cardBanHang");
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
         
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
       
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        System.exit(WIDTH);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void btnViewPhieuGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPhieuGiamGiaActionPerformed
        cardLayout.show(cards,"cardPhieuGiamGia");
    }//GEN-LAST:event_btnViewPhieuGiamGiaActionPerformed

    private void btnViewHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHoaDonActionPerformed
        cardLayout.show(cards,"cardHoaDon");
    }//GEN-LAST:event_btnViewHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnViewHoaDon;
    private javax.swing.JButton btnViewNhanVien;
    private javax.swing.JButton btnViewPhieuGiamGia;
    private javax.swing.JButton btnViewSanPham;
    private javax.swing.JButton btnViewThongKe;
    private javax.swing.JButton btnViewTrangChu;
    private javax.swing.JPanel cards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblDangXuat;
    private viewChucNangChinh.ViewBanHang viewBanHang1;
    private viewChucNangChinh.ViewHoaDon viewHoaDon2;
    private viewChucNangChinh.ViewNguoiDung viewNguoiDung1;
    private viewChucNangChinh.ViewPhieuGiamGia viewPhieuGiamGia2;
    private viewChucNangChinh.ViewSanPham viewSanPham1;
    // End of variables declaration//GEN-END:variables
}
