/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewChucNangChinh;

/**
 *
 * @author Admin
 */
public class ViewKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form ViewPhieuGiamGia
     */
    public ViewKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtSdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        cboChucVu = new javax.swing.JComboBox<>();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÍ NGƯỜI DÙNG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 14, -1, -1));

        jLabel2.setText("Mã : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Tên người dùng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 110, -1, -1));

        jLabel4.setText("Năm sinh:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 150, -1, -1));

        jLabel5.setText("Chức vụ:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 110, -1, -1));

        jLabel6.setText("Giới tính");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 189, -1, -1));

        jLabel7.setText("Trạng thái:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 189, -1, -1));
        add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 67, 188, -1));
        add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 107, 188, -1));
        add(txtNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 147, 188, -1));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Còn ");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 187, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Hết");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 187, -1, -1));
        add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 147, 188, -1));

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ", "Tên người dùng", "Năm sinh", "Số điện thoại", "Giới tính", "Chức vụ", "Mật khẩu", "Ngày bắt đầu", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);
        if (tblNguoiDung.getColumnModel().getColumnCount() > 0) {
            tblNguoiDung.getColumnModel().getColumn(0).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(1).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(2).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(3).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(4).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(5).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(6).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(7).setResizable(false);
            tblNguoiDung.getColumnModel().getColumn(8).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 372, 742, 239));

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cboChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 107, 188, -1));

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");
        add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 187, -1, -1));

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });
        add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 187, -1, -1));

        jLabel8.setText("Số điện thoại");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 150, -1, -1));

        jLabel9.setText("Mật khẩu");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 70, -1, -1));
        add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 67, 188, -1));

        jLabel10.setText("Ngày bắt đầu");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 226, -1, -1));

        txtNgayBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBatDauActionPerformed(evt);
            }
        });
        add(txtNgayBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 188, -1));

        jButton1.setText("Thêm");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 274, -1, -1));

        jButton2.setText("Sửa");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 274, -1, -1));

        jButton3.setText("Xoá");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 274, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 188, 24));

        jButton4.setText("Tìm kiếm");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 331, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void txtNgayBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBatDauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
